create table if not exists contact_book
(
    contact_id        int primary key generated by default as identity,
    contact_name      varchar(20)  not null,
    contact_username  varchar(50)  not null unique,
    contact_surname   varchar(30)  not null,
    contact_age       int          not null check ( contact_age > 0 ),
    contact_phone     varchar(15)  not null unique,
    contact_email     varchar(100) not null unique,
    contact_country   varchar(150),
    contact_city      varchar(100),
    contact_address   varchar(150),
    contact_workplace varchar(150),
    contact_post      varchar(50)
);
